# Prometheus Configuration for OTLP Collector Integration
global:
  scrape_interval: 30s
  evaluation_interval: 30s

rule_files:
  # - "first_rules.yml" 
  # - "second_rules.yml"

scrape_configs:
  # Scrape the OTEL Collector metrics
  - job_name: 'otel-collector'
    static_configs:
      - targets: ['otel-collector:8888']

  # Scrape metrics exposed by the collector's prometheus exporter
  - job_name: 'quote-master-metrics'
    static_configs:
      - targets: ['otel-collector:8889']

  # Scrape Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Quote Master Pro API (via host network or direct)
  - job_name: 'quote-master-api'
    static_configs:
      - targets: ['host.docker.internal:8000']
    metrics_path: '/metrics'
    scrape_interval: 15s
    scrape_timeout: 10s

  # Redis metrics
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    scrape_interval: 30s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093